version: "3.8"
services:
  postgres:
    restart: always
    container_name: postgres
    image: postgres:15.2
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DBNAME=db
      - ALLOW_IP_RANGE=0.0.0.0/0
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - tracker

  django:
    restart: always
    container_name: django
    command: sh docker/start.sh
    environment: &django_environment
      - DATABASE_URL=postgresql://localhost:5432
      - POSTGRES_USER=admin
      - POSTGRES_PASS=password
    build:
      context: .
      dockerfile: ./docker/Dockerfile.back
    volumes: &django_volumes
      - .:/opt/tracker
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - tracker

  frontend:
    restart: always
    command: npm run start
    container_name: frontend
    environment: *django_environment
    build:
      context: .
      dockerfile: ./docker/Dockerfile.front
    volumes: *django_volumes
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - tracker

networks:
  tracker:

volumes:
  pg_data:
